### ISSUE TITLE
Execute Permissions missing in pkg for group and others.

### ISSUE THREAD

**Issue by cvgs** [brunerd/ljt#1]
Apparently `ljt-1.0.7.pkg` is not setting the executable bit for group for the two binaries `ljt` and `ljt.min`, which leads to "permission denied" when calling it from an user different than `root`. Inspecting the pkg with "Suspicious Package" shows that the `x` bit is only set for "user".

Running `chmod go+x /usr/local/ljt/ljt*` fixes that on an installed system, but the permissions should probably set in the package.

**Comment by brunerd** [comment]
D'oh! Thanks for pointing that out @cvgs! The package is fixed now.
